/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TicketBooking } from "./TicketBooking";
export * as factories from "./factories";
export { TicketBooking__factory } from "./factories/TicketBooking__factory";
